name: hadayek_hof
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.1.13
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.1
  firebase: ^9.0.3
  firebase_core: ^1.17.0
  firebase_messaging: ^11.4.0
  firebase_messaging_web: ^2.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_html: ^2.2.1
  flutter_launch: ^0.3.0
  flutter_launcher_icons: ^0.9.2
  flutter_network_connectivity: ^0.0.6
  flutter_offline: ^2.1.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_scroll_to_top: ^2.1.1
  flutter_share: ^2.0.0
  fluttertoast: ^8.0.9
  footer: ^0.0.4
  full_screen_image_null_safe: ^2.0.0
  hexcolor: ^2.0.7
  http: ^0.13.4
  open_mail_app: ^0.4.5
  rename: ^2.0.1
  rflutter_alert: ^2.0.4
  splash_screen_view: ^3.0.0
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/Site FavIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/

  fonts:
    - family: MYRIADPRO
      fonts:
        - asset: assets/fonts/Myriad Pro/MYRIADPRO-BOLD.OTF
        - asset: assets/fonts/Myriad Pro/MYRIADPRO-REGULAR.OTF
        - asset: assets/fonts/Myriad Pro/MyriadPro-Light.OTF

    - family: HSNIbtisam
      fonts:
        - asset: assets/fonts/HSN Ibtisam normal/HSN Ibtisam.ttf

    - family: NewIconsForApp
      fonts:
        - asset: assets/fonts/NewIconsForApp.ttf
